#!/usr/bin/python3
#-*- coding: utf-8 -*-
"""
使用方法：
./parser.py 节点名字 ip
"""

from __future__ import print_function
from bs4 import BeautifulSoup
import re
import pdb
import json
import sys
import requests as rq


if len(sys.argv) != 3:
    sys.exit(1)

node_name = sys.argv[1]
ip = sys.argv[2]

# Use below or the appropriate ID from IPIP.net, e.g. 7 == 天津联通
# see full server list at: view-source:https://www.ipip.net/traceroute.php
# current full list:
#"153"内蒙古呼和浩特电信
#"45"内蒙古呼和浩特联通
#"405"北京(华为云)
#"423"北京(移动)
#"80"北京(阿里云)
#"67"北京(青云QingCloud一区鲁谷机房)
#"302"北京(青云QingCloud三区A)
#"190"北京BGP(互联港湾)
#"254"北京电信(天翼云)
#"41"北京鹏博士
#"380"天津(腾讯云)
#"7"天津联通
#"134"山西晋城联通
#"247"吉林长春铁通
#"433"辽宁沈阳(天翼云)
#"118"辽宁沈阳铁通
#"15"辽宁葫芦岛联通
#"21"黑龙江哈尔滨联通
#"18"陕西宝鸡电信
#"145"陕西西安电信(天翼云)
#"22"云南怒江电信
#"318"云南昆明电信
#"133"四川乐山电信
#"305"四川德阳移动
#"304"四川成都电信(天翼云)
#"300"贵州兴义电信
#"11"重庆电信
#"12"重庆联通
#"404"武汉电信(杭州牛盾)
#"164"河南郑州联通
#"434"湖北武汉(天翼云)
#"382"上海(腾讯云)
#"249"上海(阿里云)
#"312"上海(青云QingCloud)
#"191"上海BGP(互联港湾)
#"100"上海电信(天翼云一区)
#"275"上海电信(天翼云三区)
#"356"上海移动
#"16"安徽滁州(联通/电信)
#"14"安徽芜湖电信
#"68"山东青岛(阿里云)
#"385"成都(腾讯云)
#"283"江苏南京电信(天翼云)
#"152"江苏南通电信
#"319"江苏常州BGP(蓝队网络)
#"412"江苏徐州电信（几何云）
#"413"江苏徐州联通（几何云）
#"172"江苏无锡(51IDC.COM)
#"150"江苏泰州电信(3A网络)
#"210"江苏镇江电信
#"313"江苏镇江电信(YUNDUO.IO)
#"315"江苏镇江移动
#"314"江苏镇江联通
#"212"江西上饶电信
#"211"江西南昌电信
#"96"浙江杭州(阿里云)
#"4"浙江杭州电信
#"3"浙江杭州联通
#"163"浙江金华电信
#"298"浙江金华联通
#"299"福建三明电信
#"340"福建厦门电信(天翼云厦门节点1)
#"341"福建厦门电信(天翼云厦门节点2)
#"338"福建福州电信
#"339"福建福州联通
#"63"广东中山(青云QingCloud)
#"97"广东中山电信
#"99"广东佛山电信
#"333"广东佛山电信(30CN.NET)
#"192"广东广州BGP(互联港湾)
#"274"广东广州电信(天翼云)
#"24"广东深圳(阿里云)
#"327"广东深圳天威视讯（联通）
#"326"广东深圳电信(mcplay.cn)
#"424"广州(移动)
#"381"广州(腾讯云)
#"19"广西南宁电信
#"257"台湾台中市(中华电信)
#"252"台湾台中市(亚太电信)
#"285"台湾台北市(中华电信HiCloud)
#"256"台湾台北市(远传电信)
#"406"台湾台北市CN2(66.TO)
#"289"台湾台南市(中华电信HiCloud)
#"279"台湾彰化县(GCE)
#"33"台湾新北市
#"435"澳门(CTM机房)
#"193"香港(3A网络)
#"375"香港(LeaseWeb机房@VMLINK.CC)
#"409"香港(PCCWIMSBiz)
#"301"香港(SunnyVision机房)
#"202"香港(VPS.TO)
#"386"香港(azure)
#"276"香港(中电华联机房)
#"403"香港(新立讯机房)
#"261"香港(爱淘云)
#"383"香港(腾讯云)
#"149"香港(青云QingCloud)
#"353"香港B区(阿里云)
#"124"香港电信(沙田机房)
#"253"香港电信CN2(66.TO)
#"397"印度孟买(AMAZON-LIGHTSAIL))
#"331"印度新德里
#"94"印度浦那
#"344"印度班加罗尔(DIGITALOCEAN-BLR1)
#"421"印度金奈（腾讯云／softlayer）
#"38"新加坡
#"291"新加坡(80HOST@LeaseWeb-SG)
#"396"新加坡(AMAZON-LIGHTSAIL)
#"388"新加坡(Azure)
#"221"新加坡(CONOHA)
#"157"新加坡(DIGITALOCEAN)
#"216"新加坡(LINODE)
#"322"新加坡(QuadHost)
#"223"新加坡(VPS.TO)
#"357"新加坡(VULTR)
#"263"新加坡(阿里云)
#"429"新加坡裕廊西(GCE)
#"36"日本东京
#"395"日本东京(AMAZON-LIGHTSAIL)
#"387"日本东京(Azure)
#"220"日本东京(CONOHA)
#"187"日本东京(DIX.JP)
#"425"日本东京(GCE)
#"217"日本东京(SOFTLAYER@VPS.TO)
#"188"日本东京(VPS.TO)
#"147"日本东京(VULTR)
#"359"日本东京(阿里云)
#"420"日本东京CloudGarage
#"363"日本东京都品川区(LINODE)
#"129"日本大阪
#"408"日本福冈县
#"280"柬埔寨金边
#"155"泰国曼谷
#"297"越南河内
#"215"越南胡志明市
#"362"阿联酋迪拜(阿里云)
#"411"韩国金海市
#"42"韩国首尔
#"389"韩国首尔(Azure)
#"370"韩国首尔(KDatacenter)
#"354"韩国首尔(智多互联@LG线路)
#"332"韩国首尔(蘑菇Host)
#"323"韩国首尔CN2(66.TO)
#"281"韩国首尔KT(66.TO)
#"414"韩国首尔KT(MineCloud)
#"122"马来西亚赛城(CONTROLVM)
#"125"澳大利亚布里斯班
#"109"澳大利亚悉尼
#"394"澳大利亚悉尼(AMAZON-LIGHTSAIL)
#"384"澳大利亚悉尼(腾讯云)
#"364"澳大利亚悉尼(阿里云)
#"159"澳大利亚珀斯
#"138"澳大利亚阿德莱德
#"140"丹麦哥本哈根
#"84"乌克兰基辅
#"415"以色列罗什艾因
#"372"俄罗斯哈巴罗夫斯克
#"379"俄罗斯哈巴罗夫斯克（MineCloud）
#"407"俄罗斯圣彼得堡(misaka.io)
#"141"俄罗斯圣彼得堡(vstoike.ru)
#"378"俄罗斯莫斯科
#"232"俄罗斯莫斯科(迅达云)
#"330"保加利亚瓦尔纳
#"102"保加利亚索非亚
#"93"匈牙利布达佩斯
#"418"土耳其伊斯坦布尔（80host）
#"416"土耳其布尔萨
#"419"塞尔维亚贝尔格莱德
#"85"德国慕尼黑
#"26"德国法兰克福
#"393"德国法兰克福(AMAZON-LIGHTSAIL)
#"209"德国法兰克福(DIGITALOCEAN-FRA1)
#"431"德国法兰克福(GCE)
#"250"德国法兰克福(LINODE)
#"120"德国法兰克福(VULTR)
#"361"德国法兰克福(阿里云)
#"374"德国法兰克福CN2(66.TO)
#"373"德国法兰克福（Host1Plus）
#"142"德国纽伦堡
#"179"意大利巴勒莫
#"81"意大利米兰
#"237"意大利米兰(SOFTLAYER)
#"248"挪威奥斯陆
#"128"摩尔多瓦基希讷乌
#"311"比利时圣吉斯兰(GCE)
#"376"比利时布鲁塞尔
#"82"法国巴黎
#"268"法国巴黎(ONLINE.NET)
#"244"法国斯特拉斯堡(OVH)
#"366"法国鲁贝
#"39"波兰华沙(OVH)
#"303"波兰塔尔诺夫斯凯古雷
#"106"爱尔兰都柏林
#"398"爱尔兰都柏林(AMAZON-LIGHTSAIL)
#"135"瑞典哥德堡
#"111"瑞典斯德哥尔摩
#"65"瑞士苏黎世
#"92"立陶宛维尔纽斯
#"255"立陶宛考纳斯
#"76"罗马尼亚布加勒斯特
#"121"英国伦敦
#"399"英国伦敦(AMAZON-LIGHTSAIL)
#"214"英国伦敦(DIGITALOCEAN-LON1)
#"430"英国伦敦(GCE)
#"417"英国伦敦(InceptionHosting)
#"165"英国伦敦(LINODE)
#"117"英国曼彻斯特(LOVESERVERS.COM)
#"35"荷兰阿姆斯特丹(DIGITALOCEAN-AMS1)
#"205"荷兰阿姆斯特丹(DIGITALOCEAN-AMS2)
#"206"荷兰阿姆斯特丹(DIGITALOCEAN-AMS3)
#"218"荷兰阿姆斯特丹(DmeHosting)
#"46"荷兰阿姆斯特丹(VULTR)
#"104"荷兰鹿特丹
#"213"葡萄牙里斯本
#"127"葡萄牙里斯本(LeapSwitch)
#"238"西班牙巴塞罗那
#"377"西班牙瓦伦西亚
#"273"加拿大多伦多(DIGITALOCEAN-TOR1)
#"422"加拿大多伦多（腾讯云）
#"110"加拿大温哥华
#"269"加拿大温哥华(迅达云)
#"161"加拿大蒙特利尔
#"167"墨西哥克雷塔罗
#"55"美国丹佛
#"293"美国丹佛(securedragon.net)
#"233"美国亚特兰大(FTPIT.COM)
#"182"美国亚特兰大(LINODE)
#"158"美国亚特兰大(VULTR)
#"78"美国休斯顿
#"170"美国俄克拉荷马城
#"310"美国俄勒冈州达尔斯(GCE)
#"87"美国哥伦布
#"53"美国圣何塞
#"162"美国圣何塞(VULTR)
#"358"美国圣克拉拉(CTL.IO)
#"64"美国堪萨斯
#"57"美国夏洛特
#"227"美国奥格登(httpzoom.com)
#"278"美国康瑟尔布拉夫斯(GCE)
#"410"美国弗吉尼亚阿什本(misaka.io)
#"49"美国旧金山
#"264"美国旧金山(AMAZON)
#"60"美国波士顿
#"107"美国波特兰
#"391"美国波特兰(AMAZON-LIGHTSAIL)
#"43"美国洛杉矶
#"334"美国洛杉矶(30CN.NET)
#"266"美国洛杉矶(51WEB@QUADRANET机房亚洲优化线路)
#"119"美国洛杉矶(HostSpaces@66.TO)
#"328"美国洛杉矶(PumpCloud)
#"265"美国洛杉矶(VULTR)
#"296"美国洛杉矶(ZBUSA@QUADRANET机房非亚洲优化线路)
#"295"美国洛杉矶(ZBUSA机房)
#"347"美国洛杉矶(Zenlayer/C3Edge机房@80HOST)
#"355"美国洛杉矶(voxility高防@66.TO)
#"262"美国洛杉矶(爱淘云)
#"400"美国洛杉矶CN2(66.TO)
#"203"美国皮斯卡特维
#"116"美国盐湖城
#"168"美国硅谷(阿里云)
#"222"美国纽瓦克(LINODE)
#"260"美国纽约(DIGITALOCEAN-NYC1)
#"86"美国纽约(DIGITALOCEAN-NYC2)
#"204"美国纽约(DIGITALOCEAN-NYC3)
#"44"美国芝加哥
#"225"美国芝加哥(VPSCHEAP.NET)
#"95"美国芝加哥(VULTR)
#"432"美国蒙克斯科纳(GCE)
#"72"美国西雅图
#"56"美国费利蒙
#"114"美国费城
#"103"美国达拉斯
#"52"美国达拉斯(QUADRANET机房)
#"25"美国迈阿密
#"69"美国迈阿密(VULTR)
#"390"美国都柏林(AMAZON-LIGHTSAIL)
#"27"美国阿什本
#"365"美国阿什本(AMAZON-LIGHTSAIL)
#"428"美国阿什本(GCE)
#"166"美国阿什本(SOFTLAYER)
#"360"美国阿什本(阿里云)
#"226"哥斯达黎加
#"73"巴西圣保罗
#"151"巴西圣保罗(AMAZON)
#"427"巴西圣保罗(GCE)
#"208"阿根廷布宜诺斯艾利斯
#"48"南非开普敦
#"123"南非约翰内斯堡
#"402"南非约翰内斯堡（oneprovider）
maps = {
    u'上海电信' : '275',
    'shdx' : '275',
    u'上海移动' : '356',
    'shyd' : '356',
    u'江苏联通' : '314',
    u'jslt' : '314',
    u'北京教育网' : '405',
    u'jyw' : '405',
    u'北京移动' : '423',
    u'bjyd' : '423',
    u'北京电信' : '254',
    u'bjdx' : '254',
    u'广州电信' : '99',
    u'gzdx' : '99',
    u'广州移动' : '424',
    u'gzyd' : '424',
    u'广州联通' : '327',
    u'gzlt' : '327',
}

if node_name in maps.keys():
    baseurl = "https://www.ipip.net/traceroute.php?as=1&a=get&n=1&id=%s&t=I&ip=" % maps[node_name]
else:
    try:
        int(node_name)
    except ValueError:
        sys.exit(1)
    else:
        baseurl = "https://www.ipip.net/traceroute.php?as=1&a=get&n=1&id=%s&t=I&ip=" % node_name

r = rq.get(baseurl + ip)
ft = r.text

soup = BeautifulSoup(ft, 'lxml')

scripts = soup.find_all('script')

pattern1 = re.compile('<a.*?>')
pattern2 = re.compile('<\\\/a>')
pattern3 = re.compile(r"parent.resp_once\('(\d*)', (.*)\)")

for script in scripts:
    text = script.text
    matches = pattern1.findall(text)
    if matches:
        for m in matches:
            text = text.replace(m, '')

    matches = pattern2.findall(text)
    if matches:
        for m in matches:
            text = text.replace(m, '')

    matches = pattern3.match(text)
    if matches:
        hop = int(matches.group(1))
        detail = json.loads(matches.group(2))
        ip = detail[0]['ip']
        area = detail[0]['area']
        latency = detail[0]['time']

        print("%-3s %-15s %-25s %-20s" % (hop, ip, latency, area))
