#!/bin/sh
function generate_ssr() {
  cat > /etc/ssr.json <<EOF
{
    "server": "ip_or_domain",
    "server_port": 1234,
    "local_address": "0.0.0.0",
    "local_port": 8088,
    "password": "m",
    "method": "aes-256-cfb",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "cloudflare.com,cloudfront.com",
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": true,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": true
}
EOF
}

if [ ! -f /etc/ssr.json ];
then
  generate_ssr
fi

while getopts ":s:l:S:L:p:o:O:" arg; do
  case "$arg" in
    s)
      server=$OPTARG
      ;;
    l)
      port=$OPTARG
      ;;
    S)
      local_server=$OPTARG
      ;;
    L)
      local_port=$OPTARG
      ;;
    p)
      protocol=$OPTARG
      ;;
    o)
      obfs=$OPTARG
      ;;
    O)
      obfs_param=$OPTARG
      ;;
    *)
      exit 1
  esac
done

echo server       $server
echo port         $port
echo local_server $local_server
echo local_port   $local_port
echo protocol     $protocol
echo obfs         $obfs
echo obfs_param   $obfs_param
